{% set version = "0.5.2" %}
{% set sha256 = "8da181d651a6e034070a5043c587161dccd7dc64d4c8df13557e49a6156b8c97" %}

package:
  name: micromamba
  version: {{ version }}

source:
  url: https://github.com/TheSnakePit/mamba/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  ignore_run_exports:
    - libcurl  # [unix]
    - libarchive  # [unix]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - ninja  # [win]
  host:
    - cli11
    - nlohmann_json
    # static libs
    - libcurl
    - libcurl-static
    - xz-static
    - libssh2-static
    - libarchive
    - krb5-static        # [unix]
    - libsolv-static     # [unix]
    - libopenssl-static  # [unix]
    - zstd-static  # [unix]
    - libnghttp2-static  # [unix]
    - lz4-c-static  # [unix]
    - krb5     # [win]
    - libsolv  # [win]
    - openssl  # [win]
    - cpp-filesystem

test:
  commands:
    - test -f $PREFIX/bin/micromamba  # [unix]
    - micromamba --help

about:
  home: https://github.com/TheSnakePit/mamba
  license_file:
    - LICENSE
    - CURL_LICENSE.txt
    - LIBARCHIVE_LICENSE.txt
    - KRB5_LICENSE.txt
    - LIBSOLV_LICENSE.txt
    - LIBOPENSSL_LICENSE.txt
    - CLI11_LICENSE.txt
    - NLOHMANN_JSON_LICENSE.txt
    - ZSTD_LICENSE.txt
    - LIBLZ4_LICENSE.txt
    - C_ARES_LICENSE.txt
    - LIBEV_LICENSE.txt
    - CPP_FILESYSTEM_LICENSE.txt
    - LIBNGHTTP2_LICENSE.txt
  license: BSD-3-Clause AND MIT AND OpenSSL
  license_family: BSD
  summary: Micromamba is a tiny version of mamba, the fast conda package installer.
  dev_url: https://github.com/TheSnakePit/mamba

extra:
  recipe-maintainers:
    - wolfv
    - SylvainCorlay
    - JohanMabille
