{% set version = "2.0.2" %}
{% set sha256 = "52a9ffe51d7da271cd4c5c200346f757531d9b41ef6a9ce9edc86891ce5520bd" %}
{% set build_num = 1 %}

# A strategy for testing the feedstock locally in mamba CI
{% if os.environ.get("CI", "") == "local" %}
  {% set mamba_source_type = "path" %}
  {% set mamba_source_val = "{}/source".format(os.environ.get("FEEDSTOCK_ROOT", "..")) %}
  {% set mamba_hash_type = "" %}
  {% set mamba_hash_val = "" %}
{% else %}
  {% set mamba_source_type = "url" %}
  {% set mamba_source_val = "https://github.com/mamba-org/mamba/archive/refs/tags/micromamba-{}.tar.gz".format(version) %}
  {% set mamba_hash_type = "sha256" %}
  {% set mamba_hash_val = sha256 %}
{% endif %}

# Used for writing generic tests
{% set bin_ext = "" %}      # [unix]
{% set bin_ext = ".exe" %}  # [win]

package:
  name: micromamba
  version: {{ version }}

source:
  - "{{ mamba_source_type }}": "{{ mamba_source_val }}"
    "{{ mamba_hash_type }}": "{{ mamba_hash_val }}"
    folder: mamba
  # VCPKG comes with its own (short-lived) metadata which can be already outdated in the latest release
  - url: https://github.com/microsoft/vcpkg/archive/refs/tags/2024.07.12.tar.gz  # [win]
    sha256: 7da785e42b7487fb0e7465188f12c6ce0dfa760ab334d0f4f708bd1fc54081b1     # [win]
    folder: vcpkg  # [win]

build:
  number: {{ build_num }}
  string: {{ build_num }}
  ignore_run_exports_from:
    - libcurl                     # [unix]
    - libarchive-minimal-static   # [unix]
    - openssl                     # [unix]
    - spdlog
    - fmt
    - {{ compiler('c') }}         # [linux]
    - {{ compiler('cxx') }}       # [linux]
    - python                      # [win]
    - libsolv
    - zlib

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja
    - vcpkg-tool      # [win]
    - python          # [win]
    - curl >=8.4.0    # [win]
    - zlib            # [win]
  host:
    - cli11 >=2.2,<3
    - cpp-expected
    - nlohmann_json
    - simdjson-static >=3.3.0
    - spdlog
    - fmt
    - libsolv-static >=0.7.24
    - yaml-cpp-static >=0.8.0
    - reproc-static >=14.2.4.post0
    - reproc-cpp-static >=14.2.4.post0
    - libcurl >=8.4.0              # [unix]
    - libcurl-static >=8.4.0       # [unix]
    - xz-static                    # [unix]
    - libssh2-static               # [unix]
    - libarchive-minimal-static    # [unix]
    - krb5-static                  # [unix]
    - openssl            {{ openssl }}  # [unix]
    - libopenssl-static  {{ openssl }}  # [unix]
    - zstd-static                  # [unix]
    - zlib                         # [unix]
    - libnghttp2-static            # [unix]
    - lz4-c-static                 # [unix]
    - winreg                       # [win]

test:
  commands:
    - test -f "${PREFIX}/bin/micromamba"                    # [unix]
    - test ! -f "${PREFIX}/etc/profile.d/mamba.sh"          # [unix]
    - if not exist %LIBRARY_BIN%\micromamba.exe (exit 1)  # [win]
    - micromamba{{ bin_ext }} --help
    - export MAMBA_ROOT_PREFIX="$(mktemp -d)"  # [unix]
    - mkdir %TEMP%\mamba                       # [win]
    - set "MAMBA_ROOT_PREFIX=%TEMP%\mamba"     # [win]
    - micromamba{{ bin_ext }} create -n test --override-channels -c conda-forge --yes python=3.9
    - '"${MAMBA_ROOT_PREFIX}/envs/test/bin/python" --version'       # [unix]
    - '%MAMBA_ROOT_PREFIX%\envs\test\python.exe --version'          # [win]
    - '"${MAMBA_ROOT_PREFIX}/envs/test/bin/python" -c "import os"'  # [unix]
    - '%MAMBA_ROOT_PREFIX%\envs\test\python.exe -c "import os"'     # [win]

about:
  home: https://github.com/mamba-org/mamba
  license_file:
    - mamba/LICENSE
    - CLI11_LICENSE.txt
    - CURL_LICENSE.txt
    - C_ARES_LICENSE.txt
    - FMT_LICENSE.txt
    - KRB5_LICENSE.txt
    - LIBARCHIVE_LICENSE.txt
    - LIBEV_LICENSE.txt
    - LIBLZ4_LICENSE.txt
    - LIBNGHTTP2_LICENSE.txt
    - LIBOPENSSL_3_LICENSE.txt
    - LIBOPENSSL_LICENSE.txt
    - LIBSOLV_LICENSE.txt
    - NLOHMANN_JSON_LICENSE.txt
    - REPROC_LICENSE.txt
    - SPDLOG_LICENSE.txt
    - TL_EXPECTED_LICENSE.txt
    - ZLIB_LICENSE.txt
    - ZSTD_LICENSE.txt
  license: BSD-3-Clause AND MIT AND OpenSSL
  license_family: BSD
  summary: Micromamba is a tiny version of mamba, the fast conda package installer.
  dev_url: https://github.com/mamba-org/mamba

extra:
  recipe-maintainers:
    - jjerphan
    - AntoinePrv
    - pavelzw
    - wolfv
    - SylvainCorlay
    - JohanMabille
    - mariusvniekerk
    - adriendelsalle
