{% set version = "0.7.14" %}

package:
  name: micromamba
  version: {{ version }}

source:
  - url: https://github.com/mamba-org/mamba/archive/{{ version }}.tar.gz
    sha256: bb12b96481fe483831d208667fc5516e0b1b1320708a6f8c373e328a56dcc01c
  - path: CLI11.hpp
    folder: include/mamba/CLI.hpp

build:
  number: 0
  ignore_run_exports_from:
    - libcurl                  # [unix]
    - libarchive               # [unix]
    - {{ compiler('c') }}      # [linux]
    - {{ compiler('cxx') }}    # [linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake  # [unix]
    - make   # [unix]
    - vcpkg  # [win]
  host:
    - cli11
    - cpp-filesystem
    - nlohmann_json
    - yaml-cpp-static    # [unix]
    - libcurl            # [unix]
    - libcurl-static     # [unix]
    - xz-static          # [unix]
    - libssh2-static     # [unix]
    - libarchive         # [unix]
    - krb5-static        # [unix]
    - libsolv-static     # [unix]
    - libopenssl-static  # [unix]
    - zstd-static        # [unix]
    - libnghttp2-static  # [unix]
    - lz4-c-static       # [unix]
    - reproc-static      # [unix]
    - reproc-cpp         # [unix]
    - reproc-cpp-static  # [unix]

test:
  commands:
    - test -f $PREFIX/bin/micromamba                                                    # [unix]
    - micromamba --help
    - "export TMPDIR=\"${TMPDIR:-/tmp}\""                                               # [unix and not (ppc64le or aarch64)]
    - "if [ ! -d \"${TMPDIR}\" ]; then mkdir -p \"${TMPDIR}\"; fi"                      # [unix and not (ppc64le or aarch64)]
    - stat $TMPDIR                                                                      # [unix and not (ppc64le or aarch64)]
    - export MAMBA_ROOT_PREFIX=$TMPDIR/mamba                                            # [unix and not (ppc64le or aarch64)]
    - micromamba create -p $TMPDIR/testenv -c conda-forge -c defaults --yes python=3.9  # [unix and not (ppc64le or aarch64)]
    - $TMPDIR/testenv/bin/python --version                                              # [unix and not (ppc64le or aarch64)]
    - $TMPDIR/testenv/bin/python -c 'import ssl'                                        # [unix and not (ppc64le or aarch64)]

about:
  home: https://github.com/mamba-org/mamba
  license_file:
    - LICENSE
    - CURL_LICENSE.txt
    - LIBARCHIVE_LICENSE.txt
    - KRB5_LICENSE.txt
    - LIBSOLV_LICENSE.txt
    - LIBOPENSSL_LICENSE.txt
    - CLI11_LICENSE.txt
    - NLOHMANN_JSON_LICENSE.txt
    - ZSTD_LICENSE.txt
    - LIBLZ4_LICENSE.txt
    - C_ARES_LICENSE.txt
    - LIBEV_LICENSE.txt
    - CPP_FILESYSTEM_LICENSE.txt
    - LIBNGHTTP2_LICENSE.txt
  license: BSD-3-Clause AND MIT AND OpenSSL
  license_family: BSD
  summary: Micromamba is a tiny version of mamba, the fast conda package installer.
  dev_url: https://github.com/mamba-org/mamba

extra:
  recipe-maintainers:
    - wolfv
    - SylvainCorlay
    - JohanMabille
    - mariusvniekerk
