{% set version = "1.4.0" %}
{% set build_num = 0 %}

package:
  name: micromamba
  version: {{ version }}

source:
  url: https://github.com/mamba-org/mamba/archive/refs/tags/micromamba-{{ version }}.tar.gz
  sha256: 890f37e7f84e81b85976d0a26d171406dbbbb02416efcb95bda9f263e10c21b4

build:
  number: {{ build_num }}
  string: {{ build_num }}
  ignore_run_exports_from:
    - libcurl                     # [unix]
    - libarchive-minimal-static   # [unix]
    - reproc-cpp                  # [unix]
    - openssl                     # [unix]
    - spdlog
    - fmt
    - {{ compiler('c') }}         # [linux]
    - {{ compiler('cxx') }}       # [linux]
    - python                      # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake        # [unix]
    - ninja
    - vcpkg        # [win]
    - python       # [win]
    - curl >=7.87  # [win]
    - zlib         # [win]
  host:
    - cli11 >=2.2,<3
    - cpp-expected
    - nlohmann_json
    - spdlog
    - fmt
    - yaml-cpp-static              # [unix]
    - libcurl >=7.88.1             # [unix]
    - libcurl-static >=7.88.1      # [unix]
    - xz-static                    # [unix]
    - libssh2-static               # [unix]
    - libarchive-minimal-static    # [unix]
    - krb5-static                  # [unix]
    - libsolv-static               # [unix]
    - openssl            {{ openssl }}  # [unix]
    - libopenssl-static  {{ openssl }}  # [unix]
    - zstd-static                  # [unix]
    - libnghttp2-static            # [unix]
    - lz4-c-static                 # [unix]
    - reproc-static                # [unix]
    - reproc-cpp                   # [unix]
    - reproc-cpp-static            # [unix]
    - winreg                       # [win]

test:
  commands:
    - test -f $PREFIX/bin/micromamba                                          # [unix]
    - micromamba --help
    - export TMPDIR="${TMPDIR:-/tmp}"                                         # [unix and not (ppc64le or aarch64)]
    - if [ ! -d "${TMPDIR}" ]; then mkdir -p "${TMPDIR}"; fi                  # [unix and not (ppc64le or aarch64)]
    - stat $TMPDIR                                                            # [unix and not (ppc64le or aarch64)]
    - export MAMBA_ROOT_PREFIX=$TMPDIR/mamba                                  # [unix and not (ppc64le or aarch64)]
    - micromamba create -p $TMPDIR/testenv --override-channels -c conda-forge --yes python=3.9    # [unix and not (ppc64le or aarch64)]
    - $TMPDIR/testenv/bin/python --version                                    # [unix and not (ppc64le or aarch64)]
    - $TMPDIR/testenv/bin/python -c 'import ssl'                              # [unix and not (ppc64le or aarch64)]

about:
  home: https://github.com/mamba-org/mamba
  license_file:
    - LICENSE
    - CURL_LICENSE.txt
    - LIBARCHIVE_LICENSE.txt
    - KRB5_LICENSE.txt
    - LIBSOLV_LICENSE.txt
    - LIBOPENSSL_LICENSE.txt
    - LIBOPENSSL_3_LICENSE.txt
    - CLI11_LICENSE.txt
    - NLOHMANN_JSON_LICENSE.txt
    - ZSTD_LICENSE.txt
    - LIBLZ4_LICENSE.txt
    - C_ARES_LICENSE.txt
    - LIBEV_LICENSE.txt
    - LIBNGHTTP2_LICENSE.txt
    - REPROC_LICENSE.txt
    - SPDLOG_LICENSE.txt
    - FMT_LICENSE.txt
    - TL_EXPECTED_LICENSE.txt
  license: BSD-3-Clause AND MIT AND OpenSSL
  license_family: BSD
  summary: Micromamba is a tiny version of mamba, the fast conda package installer.
  dev_url: https://github.com/mamba-org/mamba

extra:
  recipe-maintainers:
    - wolfv
    - SylvainCorlay
    - JohanMabille
    - mariusvniekerk
    - adriendelsalle
