{% set version = "0.4.1" %}
{% set sha256 = "985e8de16d64ec1bc90104f0c701500fa70f7f2eb1c7b79c7aea9a6876248e8d" %}

package:
  name: micromamba
  version: {{ version }}

source:
  url: https://github.com/TheSnakePit/mamba/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - placeholder.patch

build:
  number: 1
  ignore_run_exports:
    - libcurl  # [unix]
    - libarchive  # [unix]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - ninja  # [win]
  host:
    - cli11
    - nlohmann_json
    # static libs
    - libcurl
    - libarchive
    - krb5-static  # [unix]
    - libsolv-static  # [unix]
    - libopenssl-static  # [unix]
    - krb5  # [win]
    - libsolv  # [win]
    - openssl  # [win]

test:
  commands:
    - test -f $PREFIX/bin/micromamba  # [unix]
    - micromamba --help

about:
  home: https://github.com/TheSnakePit/mamba
  license_file:
    - LICENSE
    - CURL_LICENSE.txt
    - LIBARCHIVE_LICENSE.txt
    - KRB5_LICENSE.txt
    - LIBSOLV_LICENSE.txt
    - LIBOPENSSL_LICENSE.txt
    - CLI11_LICENSE.txt
    - NLOHMANN_JSON_LICENSE.txt
  license: BSD-3-Clause
  license_family: BSD
  summary: Micromamba is a tiny version of mamba, the fast conda package installer.
  dev_url: https://github.com/TheSnakePit/mamba

extra:
  recipe-maintainers:
    - wolfv
    - SylvainCorlay
    - JohanMabille
